project: 
  type: website
  
website: 
  page-navigation: true
  title: "VEDA Documentation" 
  site-url: "https://nasa-impact.github.io/veda-docs" 
  repo-url: https://github.com/nasa-impact/veda-docs 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2022"
    
  sidebar:
    logo: "images/Veda_logo_blue_no_text.png"
    pinned: true
    align: center
    tools: 
      - icon: info-circle
        href: https://www.earthdata.nasa.gov/esds/veda
        text: "earthdata.nasa.gov/esds/veda"
      - icon: github
        href: https://github.com/nasa-impact/veda-docs
        text: "Repository home"
      - icon: binoculars
        href: https://earthdata.nasa.gov/dashboard
        text: "VEDA Dashboard"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - veda-apis.qmd
      - section: example-notebooks/index.qmd
        contents: 
          - example-notebooks/list-collections.ipynb

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
